Task 1 is done
kznts9v-1lya/formal-lang-course pull request #1
Opened 2021-09-03 22:01 UTC by kznts9v-1lya

- Fork created
- Implemented initial utilities for working with graphs
- Implemented unit tests
- Pre-commit is configured
- GitHub Actions is configured

2021-09-06 13:10 UTC, vdshk requested changes
Также есть пара глобальных замечаний.

* Запускаться `REPL` должен через `python -m project`. Сейчас так не работает.

* >   - [x] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах.

    Именно **по имени**. В наборе данных у графов есть имена. Такие как `geospecies`, `pizza`, `enzyme`. См. [Get a real graph](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#get-a-real-graph)
    
* Копируйте из `tasks` полностью описание задачи в комментарий вашего PR и проставляйте чекбоксики, пожалуйста. Так будет и вам и мне проще видеть, что требовалось сделать и что уже сделано.

* Не забудьте написать в `project/README.md` как запускать ваше **консольное приложение**.

* Убедитесь, что ваши тесты покрывают все возможные крайние случаи.
    
> Мой комментарий на русском языке, так как курс читается на русском языке.
Если вы согласны перейти на английский, напишите мне об этом, пожалуйста, в комментариях.

2021-09-06 13:10 UTC, vdshk commented on project/__main__.py
> +    main()
Запустил из корня репозитория `python3 -m project` и получил
```
ModuleNotFoundError: No module named 'console_app'
```
Кажется так не должно быть. Или я что-то сделал не так?

2021-09-06 13:10 UTC, vdshk commented on project/console_app.py
> +command_names = ("exit", "graph_description", "two_cycles_graph")
По заданию у вас должны быть следующие команды. (названия примерные)
"get_graph_info", "create_two_cycles_graph", "save_to_dot", "quit"

2021-09-06 13:10 UTC, vdshk commented on project/console_app.py
> +def analyse_input(inputs):
Используйте [`NumPy docstrings`](https://numpydoc.readthedocs.io/en/latest/format.html).
Минимально требуется: `1. Short summary`, `4. Parameters`, `5. Returns` или `6. Yields`

2021-09-06 13:10 UTC, vdshk commented on project/console_app.py
> +def analyse_input(inputs):
Так должны быть задокументированы все функции и классы

2021-09-06 13:10 UTC, vdshk commented on requirements.txt
> +networkx~=2.6.2
`networkx` уже есть в зависимостях у `cfpq_data`. Почему вы его добавили?
```suggestion
```

2021-09-06 13:10 UTC, vdshk commented on requirements.txt
> +pytest~=6.2.5
А это для чего вы добавили?

2021-09-06 13:10 UTC, vdshk commented on tests/test_graph_tools.py
> +        randint(25, 49), randint(1, 24), verbose=False
Если вы не устанавливаете `seed` для рандом, то можете получать разные графы и тест становится недетерминированным.

2021-09-06 13:10 UTC, vdshk commented on tests/test_graph_tools.py
> +    assert desc.edge_labels == cfpq_data.get_labels(graph)
1. В unit тестах лучше придерживаться правила один `assert` на тест.
2. Ваш тест неправильно построен. Должен быть виксированный `g_info_expected` например. А так получается, что вы сравниваете одно и то же.
3. Порядок сравнения должен быть `assert actual == expected`

2021-09-06 13:10 UTC, vdshk commented on tests/test_graph_tools.py
> +    assert os.path.exists(path)
Стоит также проверять, что то, что вы сохранили совпадает с тем, что вы ожидаете увидеть в файле.

2021-09-06 13:29 UTC, kznts9v-1lya commented on requirements.txt
> +pytest~=6.2.5
Было добавлено через `pip freeze`, убираю

2021-09-06 13:29 UTC, kznts9v-1lya commented on requirements.txt
> +networkx~=2.6.2
И правда, убираю

2021-09-06 13:31 UTC, kznts9v-1lya commented on tests/test_graph_tools.py
> +        randint(25, 49), randint(1, 24), verbose=False
Возвращаю детерминированность

2021-09-06 14:15 UTC, kznts9v-1lya commented on tests/test_graph_tools.py
> +    assert os.path.exists(path)
Хорошо, добавлю

2021-09-06 14:16 UTC, kznts9v-1lya commented on tests/test_graph_tools.py
> +    assert desc.edge_labels == cfpq_data.get_labels(graph)
Изменил

2021-09-06 14:17 UTC, kznts9v-1lya commented on project/__main__.py
> +    main()
Проблема была в `import project.*`, добавил

2021-09-06 16:45 UTC, kznts9v-1lya commented on project/console_app.py
> +command_names = ("exit", "graph_description", "two_cycles_graph")
Понял, разделю функции

2021-09-06 17:17 UTC, kznts9v-1lya commented on project/__init__.py
> -print("import sources directory")
Сделаю

2021-09-06 17:38 UTC, kznts9v-1lya commented
Вадим, все замечания исправлены.

2021-09-06 17:44 UTC, kznts9v-1lya reviewed
Вадим, все замечания исправлены.
Что касается языка общения, думаю, лучше будет русский. Однако readme и документацию я опишу на английском, как полагается.

2021-09-06 17:50 UTC, vdshk commented on project/console_app.py
> +def analyse_input(inputs):
Что-то я не вижу, чтобы у всех функций и классов появилась минимальная документация, как написано в комментарии выше.

2021-09-06 17:52 UTC, kznts9v-1lya commented on project/console_app.py
> +def analyse_input(inputs):
Извиняюсь, только что заметил. Сейчас буду изучать и доделывать.

2021-09-07 06:46 UTC, vdshk commented
- Изменения увидел. Стало сильно лучше :+1:

- > Не забудьте написать в project/README.md как запускать ваше консольное приложение.

  Это не увидел.

2021-09-07 07:27 UTC, kznts9v-1lya commented
Добавил README

2021-09-07 16:48 UTC, vdshk requested changes
В целом всё супер. Нужно исправить два мелких замечания и будет зачтено.

2021-09-07 17:08 UTC, kznts9v-1lya commented on tests/test_graph_tools.py
> +        or str(actual_desc.edge_labels) == str(expected_desc.edge_labels)
Проверяю невыполнение 3-х условий по замечанию иметь 1 assert за тест

2021-09-07 17:09 UTC, kznts9v-1lya commented on tasks/task1.md
Верну

2021-09-07 17:26 UTC, vdshk commented on tests/test_graph_tools.py
> +        or str(actual_desc.edge_labels) == str(expected_desc.edge_labels)
Вам не кажется, что должен быть `and`?

2021-09-07 17:46 UTC, kznts9v-1lya commented on tests/test_graph_tools.py
> +        or str(actual_desc.edge_labels) == str(expected_desc.edge_labels)
Точно...

2021-09-08 08:13 UTC, vdshk commented
Исправления увидел. Запросите повторно ревью и смогу зачесть.

2021-09-08 13:03 UTC, vdshk requested changes
У вас какая-то беда с импортами. Поправьте пожалуйста. Всё остальное отлично.

Как исправите импорты, - зачту.

2021-09-08 13:03 UTC, vdshk commented on project/console_app.py
> +import project.console_commands as commands
```suggestion
from project.console_commands import *
```

2021-09-08 13:03 UTC, vdshk commented on project/console_commands.py
> +__all__ = []
```suggestion
from project.graph_tools import *

__all__ = [
    "exit_repl",
    "get_graph_description",
    "get_two_cycles_graph",
    "save_graph_to_dot",
    "get_graph_names",
]
```

2021-09-08 13:08 UTC, kznts9v-1lya commented on project/graph_tools.py
> +from networkx import MultiDiGraph
Хотел красивее описать сигнатуры функций, уберу

2021-09-08 13:12 UTC, kznts9v-1lya commented on project/console_commands.py
> +__all__ = []
Не хотел, чтобы можно было импортировать данные функции, так как это внутренняя часть модуля, но так уж и быть

2021-09-08 13:20 UTC, vdshk approved these changes
Молодец :+1:

> Советую, чтобы не сохранять все исправления в истории, сделать `Squash and merge`

2021-09-08 13:23 UTC, merged